[workspace]
resolver = "3"
members = [
    "crates/paw_bin",
    "crates/paw_classfile",
    # "crates/paw_lir",
    "crates/paw_mutf8",
]

[workspace.package]
version = "0.0.1-dev"
edition = "2024"

[workspace.dependencies]
paw_mutf8 = { path = "crates/paw_mutf8" }
paw_classfile = { path = "crates/paw_classfile" }
paw_lir = { path = "crates/paw_lir" }

byteorder = "1.5.0"
thiserror = "1.0.69"
eyre = "0.6.12"
color-eyre = "0.6.5"
bytemuck = {version = "1.24.0", features = ["derive", "min_const_generics"]}
num-conv = "0.2.0"
bitflags = "2.10.0"
paste = "1.0.15"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
too_many_lines = "allow"
missing_errors_doc = "allow"
missing-panics-doc = "allow"
upper_case_acronyms = "allow"
uninlined_format_args = "allow" # if there was inlined_format_args = "forbid" i would >:c
verbose_bit_mask = "allow" # literally just harder to read
manual_range_contains = "allow" # stupid lint

# On positive comparisons this is good!
# On negative ones it makes skimming harder
len_zero = "allow"

# explicit is good actually
explicit_iter_loop = "allow"

# useful to check manually every once in a while, but often should be ignored
similar_names = "allow"

wildcard_imports = "deny"

cast_possible_truncation = "deny"
cast_possible_wrap = "deny"
cast_precision_loss = "deny"
cast_lossless = "deny"
cast_sign_loss = "deny"

unreadable_literal = "deny"

[profile.release-with-debug]
inherits = "release"
debug = true
