[package]
name = "paw_classfile_lir"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
paw_mutf8.workspace = true
paw_classfile_format.workspace = true

byteorder.workspace = true
thiserror.workspace = true
bytemuck.workspace = true
eyre.workspace = true
color-eyre.workspace = true
num-conv.workspace = true
bitflags.workspace = true
