[package]
name = "paw_classfile_format"
version.workspace = true
edition.workspace = true

[dependencies]
byteorder.workspace = true
thiserror.workspace = true
bytemuck.workspace = true
paw_mutf8 = { path = "../paw-mutf8" }
num-conv = "0.2.0"
eyre = "0.6.12"
color-eyre = "0.6.5"
bitflags = "2.10.0"
paste = "1.0.15"
