[package]
name = "paw_classfile_lir"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
paw_classfile_format = { path = "../paw-classfile-format" }
paw_mutf8 = { path = "../paw-mutf8" }

byteorder.workspace = true
thiserror.workspace = true
bytemuck.workspace = true
eyre.workspace = true
color-eyre.workspace = true

bitflags = "2.10.0"
